### ISSUE TITLE
Result Evaluation

### ISSUE THREAD

**Issue by waiyc** [xyjbaal/FPCC#1]
Hi,

I saw that there is a function `eval_3d_perclass()` in `test_utils.py` for evaluation.
Can you let me know on how to use this function to evaluate the performance ?

**Comment by xyjbaal** [comment]
eval_3d_perclass() is used to calculate the averange precision.
test_utils.py is from the code of SGPN.  I did not use this function to evaluate our performance.
I used eval_iou_accuracy.py to calculate precision and recall.

Sorry, I seem to forget to upload eval_iou_accuracy.py, but it's OK now

**Comment by waiyc** [comment]
Thank you. I will close this for now
