### ISSUE TITLE
How to get the segmented points？

### ISSUE THREAD

**Issue by slowlypasser** [xyjbaal/FPCC#12]
I run the fpcc_test.py，and get the results.I only see the center score prediction，but i want to get the instance prediction.Can you tell me how to get the instance predition?Thanks!

**Comment by xyjbaal** [comment]
The code of output instance prediction is written in L294 of fpcc_test.py.
cloud you check this part again?

**Comment by slowlypasser** [comment]
> The code of output instance prediction is written in L294 of fpcc_test.py. cloud you check this part again?

I have seen that,but i use open3d to visualize all the results(all the ".txt" files).The point clouds are same like this.
![image](https://user-images.githubusercontent.com/50401260/191199202-dba21ddc-d584-466b-88a2-5e21b3690b9d.png)

**Comment by xyjbaal** [comment]
Could you tell me the name of .txt file? xxxx_grouppred.txt or xxxx_pred.txt?

**Comment by slowlypasser** [comment]
> Could you tell me the name of .txt file? xxxx_grouppred.txt or xxxx_pred.txt?
Yes,xxxx_grouppred.txt and xxxx_pred.txt is same.So does the test file.
Like 0000_026.txt  0000_026_grouppred.txt  0000_026_pred.txt,they are the same in visualization.

**Comment by slowlypasser** [comment]
> > Could you tell me the name of .txt file? xxxx_grouppred.txt or xxxx_pred.txt?
> > Yes,xxxx_grouppred.txt and xxxx_pred.txt is same.So does the test file.
> > Like 0000_026.txt  0000_026_grouppred.txt  0000_026_pred.txt,they are the same in visualization.

I want to get the result like the paper,and then extract the instance one by one.
![image](https://user-images.githubusercontent.com/50401260/191201878-2d92cd24-f674-47da-8986-47d839b5a656.png)

**Comment by xyjbaal** [comment]
I suppose there are 6 columns in _grouppred.txt. the first three columns are the coordinates of the point and the last three columns should be RGB.

for _pred.txt, the last column is the predicted instance label.

**Comment by slowlypasser** [comment]
> I suppose there are 6 columns in _grouppred.txt. the first three columns are the coordinates of the point and the last three columns should be RGB.
> 
> for _pred.txt, the last column is the predicted instance label.

Ok,i get it.Maybe,it's the problem of visualization.I will try to visualize it using aother ways.

**Comment by xyjbaal** [comment]
That's great. Maybe you can try using CloudCompare. it is a free software.
