### ISSUE TITLE
Instance segmentation to 6D pose

### ISSUE THREAD

**Issue by BharathRajM** [xyjbaal/FPCC#13]
I see that you output the instance segmentation but is there a way to extract 6D pose too from your results?

**Comment by xyjbaal** [comment]
I think there are two ways to extract 6D pose. One way is to estimate the 6D pose from the predicted individual instance by some methods, such as network or point pair feature. The other way is to add a parallel branch network to predict the 6D pose of each point (reference https://github.com/lvwj19/PPR-Net-plus).

**Comment by BharathRajM** [comment]
Perfect, got it. Thanks!
I have just started playing around with PPR-Net++ and I see that they also have a set of hyper-parameters to bridge the sim-to-real gap. Is something like that implemented with FPCC?

**Comment by xyjbaal** [comment]
I didn't implement it with FPCC.
The hyper-parameters to bridge the sim-to-real gap might be some noise added to the synthetic data. It can sometimes be called data augmentation.
