### ISSUE TITLE
parameter.json and d_max of Obeject ABC

### ISSUE THREAD

**Issue by Tianyang-Qian** [xyjbaal/FPCC#15]
Hello, I think your article is great and I want to learn more deeply. Now I have encountered several problems:

1.I wanted to use IPA Dataset but needed parameter.json at runtime,  https://github.com/xyjbaal/FPCC/issues/4   The webpage mentioned in is only Bunny's parameter.json. Can I use this instead, because I don't know the parameters required for this json file? Other .json file in the webpage don't make code work properly.

2.What is the appropriate "d_max" value for Object A, B, and C? I tried to train with 0.18, but the effect was not very good. Does "d_max" refer to the maximum width of the part?

3.Does the order in the datas/*_train.txt file have any effect on the training effect？

thanks

**Comment by xyjbaal** [comment]
Hi,

Thanks for your attention to our work.

> A1:

I'm not quite sure where our code uses the parameter.json. 
I remember that the parameter.json is used to deal with the symmetric pose of the object. 
If you don't care about the pose of object, you can use Bunny's parameter.json.

> A2:

Yes, d_max is the maximum width of the part. But for object gear, I used a  smaller value.

> A3:

I don't think the datas/*_train.txt file has any effect on the training effect. 

Thanks

**Comment by Tianyang-Qian** [comment]
Thank you for your answer and look forward to your future work.
